use super::*;

// ── Off-thread snapshot replay builder (FR1/FR6/NFR2/NFR3) ──

/// TS-1: the pure builder is grid/scrollback/marks-identical to the
/// in-place `reset_and_replay` + drain path for a representative payload
/// (text, prompt marks, scrollback growth).
#[test]
fn test_build_from_snapshot_matches_reset_and_replay() {
    // Many newlines push lines into scrollback; OSC 133 A/B/C/D emit
    // prompt marks; plain text fills the grid.
    let mut payload: Vec<u8> = Vec::new();
    payload.extend_from_slice(b"\x1b]133;A\x07prompt$ \x1b]133;B\x07");
    payload.extend_from_slice(b"echo hi\x1b]133;C\x07\r\n");
    for i in 0..40u32 {
        payload.extend_from_slice(format!("line {i}\r\n").as_bytes());
    }
    payload.extend_from_slice(b"\x1b]133;D;0\x07tail here");

    // Synchronous path: an already-used core, reset_and_replay'd + drained.
    let mut sync_core = TerminalCore::new(80, 24, 1000);
    // Dirty it first so the reset inside reset_and_replay has to clean up.
    sync_core.process_pty_data_fully(b"garbage that gets reset away\r\n\r\n");
    let sync_actions = sync_core.reset_and_replay(&payload);
    let sync_evicted = sync_core.get_scrollback_evicted_total();
    let sync_prompts = sync_core.take_prompt_marks();
    let sync_folds = sync_core.take_fold_marks();

    // Off-thread builder path.
    let never = std::sync::atomic::AtomicBool::new(false);
    let built = TerminalCore::build_from_snapshot(80, 24, 1000, &payload, &[], &never)
        .expect("not cancelled");

    assert_eq!(grid_fingerprint(&built.core), grid_fingerprint(&sync_core));
    assert_eq!(built.actions, sync_actions);
    assert_eq!(built.evicted_total, sync_evicted);
    assert_eq!(built.prompt_marks, sync_prompts);
    assert_eq!(built.fold_marks, sync_folds);
}

/// TS-2: empty payload yields the same (empty, freshly-reset) result via
/// both paths.
#[test]
fn test_build_from_snapshot_empty_payload() {
    let mut sync_core = TerminalCore::new(80, 24, 100);
    let sync_actions = sync_core.reset_and_replay(b"");
    let sync_evicted = sync_core.get_scrollback_evicted_total();
    let sync_prompts = sync_core.take_prompt_marks();
    let sync_folds = sync_core.take_fold_marks();

    let never = std::sync::atomic::AtomicBool::new(false);
    let built =
        TerminalCore::build_from_snapshot(80, 24, 100, b"", &[], &never).expect("not cancelled");

    assert_eq!(grid_fingerprint(&built.core), grid_fingerprint(&sync_core));
    assert_eq!(built.actions, sync_actions);
    assert_eq!(built.evicted_total, sync_evicted);
    assert!(built.prompt_marks.is_empty());
    assert!(built.fold_marks.is_empty());
    assert_eq!(sync_prompts.len(), built.prompt_marks.len());
    assert_eq!(sync_folds.len(), built.fold_marks.len());
}

/// Regression: a DA1/DSR/XTWINOPS query baked into snapshot bytes (e.g.
/// because some past program in the pane's scrollback wrote `\x1b[c` to
/// `/dev/tty`) must NOT leave a residual reply in the built core's
/// `response_buffer`. Otherwise the first live `take_response` after the
/// swap picks it up and delivers a stale `\x1b[?65;1;4;22c` to the live
/// shell's stdin — which zsh/zle interprets as "ESC[? prefix + literal
/// `65;1;4;22c`", inserting the parameter tail at the prompt on the
/// user's first keystroke after a window switch.
#[test]
fn test_build_from_snapshot_drains_device_response_buffer() {
    // Scrollback-shaped payload with an embedded DA1 query (`CSI c`) plus
    // a CPR query (`CSI 6 n`) — both produce buffered replies in
    // term_core when parsed.
    let mut payload = Vec::new();
    payload.extend_from_slice(b"line one\r\n");
    payload.extend_from_slice(b"\x1b[c"); // DA1 → `\x1b[?65;1;4;22c`
    payload.extend_from_slice(b"line two\r\n");
    payload.extend_from_slice(b"\x1b[6n"); // CPR → `\x1b[<r>;<c>R`

    let never = std::sync::atomic::AtomicBool::new(false);
    let built = TerminalCore::build_from_snapshot(80, 24, 100, &payload, &[], &never)
        .expect("not cancelled");

    assert_eq!(
        built.core.get_response_len(),
        0,
        "snapshot replay must discard device responses generated by \
         historic queries; residual bytes would leak as PtyInput on the \
         next live take_response after the swap"
    );
}

/// TS-3: the built core (and the replay result bundle) is statically
/// movable across threads, and actually survives a round trip through a
/// spawned worker thread.
#[test]
fn test_build_from_snapshot_is_send_across_threads() {
    fn assert_send<T: Send>() {}
    assert_send::<TerminalCore>();
    assert_send::<SnapshotReplay>();

    // Runtime proof: build on a worker, move the result back.
    let payload = b"hello off-thread\r\nsecond line\r\n".to_vec();
    let handle = std::thread::spawn(move || {
        static NEVER: std::sync::atomic::AtomicBool = std::sync::atomic::AtomicBool::new(false);
        TerminalCore::build_from_snapshot(80, 24, 100, &payload, &[], &NEVER)
    });
    let built = handle
        .join()
        .expect("worker thread panicked")
        .expect("not cancelled");
    assert_eq!(built.core.get_cell_char(0, 0), "h");
    assert!(built.core.callbacks.is_none());
}

/// A `build_from_snapshot` whose cancel flag is already set bails at the
/// first resume-loop boundary and returns `None` (a superseded off-thread
/// worker discards its work). A clear flag returns `Some` as usual.
#[test]
fn test_build_from_snapshot_cancelled_returns_none() {
    let payload = b"row zero\r\nrow one\r\n".to_vec();

    let cancelled = std::sync::atomic::AtomicBool::new(true);
    assert!(
        TerminalCore::build_from_snapshot(80, 24, 100, &payload, &[], &cancelled).is_none(),
        "a pre-set cancel flag must abandon the build"
    );

    let live = std::sync::atomic::AtomicBool::new(false);
    assert!(
        TerminalCore::build_from_snapshot(80, 24, 100, &payload, &[], &live).is_some(),
        "a clear cancel flag must build normally"
    );
}

/// TS-5 (FR2): the snapshot-replay bypass intentionally does not
/// populate scrollback content, but the returned core's
/// `scrollback_capacity` is the caller-requested `scrollback_lines` so
/// subsequent live PTY appends accumulate into scrollback exactly as
/// they do today.
#[test]
fn test_build_from_snapshot_restores_scrollback_capacity() {
    // Build a payload that scrolls many viewport rows off the top.
    // With rows=24, 100 newlines push 100 - 24 = 76 rows past the
    // viewport. (We just need > 24 to exercise scrolling; the exact
    // number is unimportant.)
    let mut payload = Vec::new();
    for i in 0..200u32 {
        payload.extend_from_slice(format!("line {i}\r\n").as_bytes());
    }
    let scrollback_lines: u32 = 10_000;
    let never = std::sync::atomic::AtomicBool::new(false);
    let built = TerminalCore::build_from_snapshot(80, 24, scrollback_lines, &payload, &[], &never)
        .expect("not cancelled");
    let mut core = built.core;
    // Immediately after replay: scrollback contents are NOT populated.
    assert_eq!(
        core.scrollback_count(),
        0,
        "snapshot-replay bypass leaves scrollback contents empty (FR2)"
    );
    // But the capacity is the caller-requested value, so live appends
    // accumulate normally.
    assert_eq!(core.scrollback_capacity(), scrollback_lines);

    // Now feed N more lines through the live PTY path. The first 24 stay
    // in the viewport; subsequent lines flow into scrollback.
    let n_extra = 100u32;
    let mut extra = Vec::new();
    for i in 0..n_extra {
        extra.extend_from_slice(format!("post {i}\r\n").as_bytes());
    }
    let _ = core.process_pty_data_fully(&extra);
    // After the live drain: scrollback fills up to `min(n_extra, scrollback_lines)`.
    // (Each `\r\n` after the viewport fills generates one scrollback row.)
    let expected_scrollback = (n_extra as usize).min(scrollback_lines as usize);
    // We pushed n_extra lines; the last `rows-1` may stay in the viewport
    // depending on cursor positioning, so accept a small slack — what we
    // really want to assert is "scrollback grew, and is bounded by
    // scrollback_lines".
    assert!(
        core.scrollback_count() > 0,
        "live PTY appends must accumulate into scrollback after the bypass is disabled"
    );
    assert!(
        core.scrollback_count() <= expected_scrollback,
        "scrollback_count={} must not exceed scrollback_lines={}",
        core.scrollback_count(),
        scrollback_lines
    );
}

/// TS-13 (FR1 / D1 v2): `SnapshotReplay.evicted_total` produced by
/// `build_from_snapshot` is byte-identical to the synchronous
/// `reset_and_replay` path on the same payload + capacity, including
/// when the payload scrolls strictly more rows than the capacity
/// (S > small_C → evicted_total == S - small_C).
#[test]
fn test_build_from_snapshot_bypass_preserves_evicted_total() {
    // 24-row viewport, scrollback_lines=5 (small_C). 50 newlines push
    // 50 lines past the viewport; the first 50 - 5 = 45 of those get
    // evicted from the scrollback ring.
    let mut payload = Vec::new();
    for i in 0..50u32 {
        payload.extend_from_slice(format!("line {i}\r\n").as_bytes());
    }
    let small_c: u32 = 5;
    // Synchronous path: build the same value via reset_and_replay on a
    // fresh core of the same size.
    let mut sync_core = TerminalCore::new(80, 24, small_c);
    sync_core.reset_and_replay(&payload);
    let sync_evicted = sync_core.get_scrollback_evicted_total();

    // build_from_snapshot path: the bypass must produce the same
    // `evicted_total`.
    let never = std::sync::atomic::AtomicBool::new(false);
    let built = TerminalCore::build_from_snapshot(80, 24, small_c, &payload, &[], &never)
        .expect("not cancelled");
    assert_eq!(
        built.evicted_total, sync_evicted,
        "bypass path must preserve evicted_total byte-identically"
    );
}

/// TS-15 (FR1 + FR3 / D1 v2): per-mark `abs_row` and `evicted_total` on
/// the `prompt_marks` (and `fold_marks`) drained by `build_from_snapshot`
/// must match the synchronous `reset_and_replay` path byte-identically,
/// including marks emitted on both sides of the `scrollback_capacity`
/// threshold (so the saturation transition in `virtual_scrollback_len` is
/// exercised).
#[test]
fn test_build_from_snapshot_bypass_preserves_mark_stamping() {
    // Construct a payload that emits OSC 133 marks BOTH before and
    // after enough scrolling to cross the scrollback_lines = small_C
    // threshold. cols=80, rows=10 viewport, small_C=5 scrollback rows.
    //
    // Sequence: first prompt mark at row 0 (no scrolling yet);
    // then 30 newlines (well past 10 viewport rows + 5 scrollback,
    // so virtual_scrollback_len saturates and evicted_total starts
    // counting); then a second prompt mark + fold begin/end.
    let mut payload = Vec::new();
    payload.extend_from_slice(b"\x1b]133;A\x07prompt1\x1b]133;B\x07ok\r\n");
    for i in 0..30u32 {
        payload.extend_from_slice(format!("line {i}\r\n").as_bytes());
    }
    payload.extend_from_slice(b"\x1b]133;A\x07prompt2\x1b]133;B\x07");
    payload.extend_from_slice(b"\x1b]777;emterm;fold;begin\x07");
    payload.extend_from_slice(b"folded text\r\n");
    payload.extend_from_slice(b"\x1b]777;emterm;fold;end\x07");
    payload.extend_from_slice(b"tail\x1b]133;D;0\x07");

    let small_c: u32 = 5;

    // Synchronous path: a fresh core of the same size, reset_and_replay,
    // then drained.
    let mut sync_core = TerminalCore::new(80, 10, small_c);
    sync_core.reset_and_replay(&payload);
    let sync_evicted = sync_core.get_scrollback_evicted_total();
    let sync_prompts = sync_core.take_prompt_marks();
    let sync_folds = sync_core.take_fold_marks();

    // build_from_snapshot path.
    let never = std::sync::atomic::AtomicBool::new(false);
    let built = TerminalCore::build_from_snapshot(80, 10, small_c, &payload, &[], &never)
        .expect("not cancelled");

    // Sanity: we exercised the saturation transition.
    assert!(
        sync_evicted > 0,
        "test payload must scroll past scrollback_lines to exercise saturation \
         (got sync_evicted={sync_evicted})"
    );
    assert!(
        !sync_prompts.is_empty(),
        "test payload must emit at least one prompt mark"
    );

    // Byte-identical mark stamping: full Vec equality covers kind, abs_row,
    // evicted_total, exit_code, label (per PendingPromptMark / PendingFoldMark
    // derive(PartialEq) shape).
    assert_eq!(built.evicted_total, sync_evicted);
    assert_eq!(built.prompt_marks, sync_prompts);
    assert_eq!(built.fold_marks, sync_folds);
}

/// TS-B (f2-fold-text-bypass-loss-tc): `build_from_snapshot` captures the
/// cursor-row text of each OSC 133 B (CommandStart) mark in
/// `SnapshotReplay.bypass_b_mark_texts` so the downstream consumer can
/// recover the command text even though the snapshot-replay bypass
/// discards scrollback contents.
///
/// The payload emits OSC 133 A → command text → OSC 133 B, then fills
/// the viewport with filler lines that scroll the B row into the (virtual,
/// discarded) scrollback. We assert:
/// 1. `bypass_b_mark_texts` is non-empty.
/// 2. At least one entry's value contains the command text "cd /tmp".
/// 3. The key of that entry matches the `abs_row` of one of the
///    `prompt_marks` with `kind == b'B'`.
#[test]
fn test_bypass_captures_b_mark_command_text() {
    // Construct a payload:
    //   OSC 133 A (PromptStart)
    //   "$ "  (prompt text)
    //   OSC 133 B (CommandStart)
    //   "cd /tmp"  (command text on the B-mark row — B fires AFTER the
    //               prompt, so the row already holds "$ cd /tmp" worth
    //               of content that was written before B arrived)
    //   "\r\n" + 50 filler lines that push the B row into scrollback
    let mut payload: Vec<u8> = Vec::new();
    payload.extend_from_slice(b"\x1b]133;A\x07$ ");
    // Write the command text before OSC 133 B so it is on the row at
    // the moment B fires (matching the real shell behaviour).
    payload.extend_from_slice(b"cd /tmp");
    payload.extend_from_slice(b"\x1b]133;B\x07");
    payload.extend_from_slice(b"\r\n");
    // Filler lines: more than viewport rows (24) so the B row scrolls off.
    for i in 0..60u32 {
        payload.extend_from_slice(format!("filler {i}\r\n").as_bytes());
    }

    let never = std::sync::atomic::AtomicBool::new(false);
    let built = TerminalCore::build_from_snapshot(80, 24, 100, &payload, &[], &never)
        .expect("not cancelled");

    // 1. The side-table must be non-empty.
    assert!(
        !built.bypass_b_mark_texts.is_empty(),
        "bypass_b_mark_texts should be populated for the B mark"
    );

    // 2. One entry's value must contain the command text.
    let has_command = built
        .bypass_b_mark_texts
        .values()
        .any(|v| v.contains("cd /tmp"));
    assert!(
        has_command,
        "bypass_b_mark_texts values should contain 'cd /tmp'; got: {:?}",
        built.bypass_b_mark_texts
    );

    // 3. Each key in bypass_b_mark_texts must match the abs_row of a B
    //    prompt mark drained from the same replay.
    let b_abs_rows: std::collections::HashSet<u32> = built
        .prompt_marks
        .iter()
        .filter(|m| m.kind == b'B')
        .map(|m| m.abs_row)
        .collect();
    for abs_row in built.bypass_b_mark_texts.keys() {
        assert!(
            b_abs_rows.contains(abs_row),
            "bypass_b_mark_texts key {abs_row} has no matching B prompt mark; \
             B marks: {:?}",
            b_abs_rows
        );
    }
}

/// TS-5 (FR1 + NFR6 — scrollback-restore):
/// `build_scrollback_only_from_snapshot` (bypass off) yields a core that
/// is byte-equivalent to a synchronous `reset_and_replay` on a fresh
/// core of the same grid / scrollback_lines.
///
/// Scope: the *full* scrollback contents (slim cells + wrapped flags),
/// `scrollback_evicted_total`, the viewport grid (via grid_fingerprint),
/// and the drained marks must all be byte-identical. The bypass-on
/// `build_from_snapshot` cannot satisfy this — its scrollback is empty
/// by design — so this test is the primary unit gate that the bypass-off
/// entry point is a drop-in replacement for the synchronous build.
#[test]
fn test_build_scrollback_only_from_snapshot_matches_sync_build() {
    // Construct a payload that scrolls some rows into scrollback so the
    // contents-equivalence check actually has rows to compare.
    let mut payload: Vec<u8> = Vec::new();
    payload.extend_from_slice(b"\x1b]133;A\x07$ ls\x1b]133;B\x07ok\r\n");
    for i in 0..50u32 {
        payload.extend_from_slice(format!("scroll {i}\r\n").as_bytes());
    }
    payload.extend_from_slice(b"tail");

    // Synchronous reference.
    let mut sync_core = TerminalCore::new(80, 24, 100);
    sync_core.reset_and_replay(&payload);
    let sync_evicted = sync_core.get_scrollback_evicted_total();
    let sync_prompts = sync_core.take_prompt_marks();
    let sync_folds = sync_core.take_fold_marks();
    let sync_slim: Vec<Vec<crate::slim_cell::SlimCell>> =
        sync_core.scrollback_slim.iter().cloned().collect();
    let sync_wrapped: Vec<bool> = sync_core.scrollback_wrapped.iter().copied().collect();

    // bypass-off off-thread build.
    let never = std::sync::atomic::AtomicBool::new(false);
    let built =
        TerminalCore::build_scrollback_only_from_snapshot(80, 24, 100, &payload, &[], &never)
            .expect("not cancelled");

    // Viewport grid + drained marks + evicted_total: byte-identical.
    assert_eq!(grid_fingerprint(&built.core), grid_fingerprint(&sync_core));
    assert_eq!(built.evicted_total, sync_evicted);
    assert_eq!(built.prompt_marks, sync_prompts);
    assert_eq!(built.fold_marks, sync_folds);
    // bypass_b_mark_texts is empty on the bypass-off path — the live
    // scrollback is the source of truth for B-mark texts (FR8).
    assert!(
        built.bypass_b_mark_texts.is_empty(),
        "bypass-off build must not populate bypass_b_mark_texts"
    );

    // Scrollback contents: cell-for-cell equality. This is what the
    // bypass-on path cannot deliver, and is the whole point of the
    // bypass-off entry.
    let built_slim: Vec<Vec<crate::slim_cell::SlimCell>> =
        built.core.scrollback_slim.iter().cloned().collect();
    let built_wrapped: Vec<bool> = built.core.scrollback_wrapped.iter().copied().collect();
    assert_eq!(
        built_slim.len(),
        sync_slim.len(),
        "scrollback row count must match"
    );
    assert_eq!(built_wrapped, sync_wrapped);
    // Cells: compare by decompressed text + width so we are robust to
    // any intern-id reassignment between the two cores (a same-style
    // entry may land on a different `style_id` slot because the build
    // orderings are not the same).
    for (row_idx, (a, b)) in built_slim.iter().zip(sync_slim.iter()).enumerate() {
        assert_eq!(a.len(), b.len(), "row {row_idx} length");
        for (col_idx, (sa, sb)) in a.iter().zip(b.iter()).enumerate() {
            let ca = crate::slim_cell::slim_to_cell(sa, &built.core.styles, &built.core.chars);
            let cb = crate::slim_cell::slim_to_cell(sb, &sync_core.styles, &sync_core.chars);
            assert_eq!(
                (ca.char_data, ca.char_len, ca.width, ca.fg, ca.bg, ca.flags),
                (cb.char_data, cb.char_len, cb.width, cb.fg, cb.bg, cb.flags),
                "row {row_idx} col {col_idx}"
            );
        }
    }
}
