use serde::{Deserialize, Serialize};

use super::types::*;

// ============================================================
// Null-safe Deserialization Helpers
// ============================================================

/// Generates a deserializer function that treats JSON null as a specific default value.
/// Each field with a custom default needs its own deserializer because serde's
/// `deserialize_with` cannot reference the `default` function.
macro_rules! deserialize_null_with {
    ($fn_name:ident, $type:ty, $default_fn:ident) => {
        fn $fn_name<'de, D>(deserializer: D) -> Result<$type, D::Error>
        where
            D: serde::Deserializer<'de>,
        {
            let opt = Option::<$type>::deserialize(deserializer)?;
            Ok(opt.unwrap_or_else($default_fn))
        }
    };
}

// Generate per-field null deserializers
deserialize_null_with!(deserialize_null_font_size, u32, default_font_size);
deserialize_null_with!(deserialize_null_padding, u32, default_padding);
deserialize_null_with!(
    deserialize_null_scrollback_lines,
    u32,
    default_scrollback_lines
);
deserialize_null_with!(deserialize_null_scroll_speed, u32, default_scroll_speed);
deserialize_null_with!(deserialize_null_true, bool, default_true);

// For fields where T::default() is correct (String, Vec, enums with #[default])
fn deserialize_null_default<'de, D, T>(deserializer: D) -> Result<T, D::Error>
where
    D: serde::Deserializer<'de>,
    T: Default + serde::Deserialize<'de>,
{
    let opt = Option::deserialize(deserializer)?;
    Ok(opt.unwrap_or_default())
}

deserialize_null_with!(deserialize_null_language, String, default_language);
deserialize_null_with!(
    deserialize_null_ui_font_family,
    String,
    default_ui_font_family
);
deserialize_null_with!(
    deserialize_null_markdown_font_size,
    u32,
    default_markdown_font_size
);
deserialize_null_with!(
    deserialize_null_markdown_body_font_family,
    String,
    default_markdown_body_font_family
);
deserialize_null_with!(
    deserialize_null_markdown_code_font_family,
    String,
    default_markdown_code_font_family
);
deserialize_null_with!(
    deserialize_null_markdown_emoji_font_family,
    String,
    default_markdown_emoji_font_family
);
deserialize_null_with!(
    deserialize_null_editor_command,
    String,
    default_editor_command
);
deserialize_null_with!(
    deserialize_null_sftp_max_concurrent_uploads,
    u16,
    default_sftp_max_concurrent_uploads
);
deserialize_null_with!(
    deserialize_null_clipboard_max_size_osc52,
    u32,
    default_clipboard_max_size_osc52
);

// ============================================================
// Default Value Functions
// ============================================================

fn default_font_size() -> u32 {
    13
}
fn default_padding() -> u32 {
    4
}
fn default_scrollback_lines() -> u32 {
    10000
}
fn default_scroll_speed() -> u32 {
    3
}
fn default_true() -> bool {
    true
}

fn default_language() -> String {
    "auto".to_string()
}
fn default_ui_font_family() -> String {
    "Roboto".to_string()
}
fn default_markdown_body_font_family() -> String {
    String::new()
}
fn default_markdown_code_font_family() -> String {
    String::new()
}
fn default_markdown_emoji_font_family() -> String {
    String::new()
}
fn default_markdown_font_size() -> u32 {
    14
}
fn default_editor_command() -> String {
    "code --goto {file}:{line}:{col}".to_string()
}
fn default_sftp_max_concurrent_uploads() -> u16 {
    4
}
fn default_clipboard_max_size_osc52() -> u32 {
    10 * 1024 * 1024 // 10 MB
}

// ============================================================
// Keybind Settings (macro-generated)
// ============================================================

/// Generates KeybindSettings struct with serde attributes, default functions,
/// null deserializers, and Default impl from a single definition table.
///
/// Each entry requires both ident and string literal forms of function names
/// because Rust's `concat!()` does not expand inside `#[serde(...)]` attributes.
macro_rules! define_keybinds {
    (
        $(
            $field:ident,
            $default_fn:ident,
            $null_deser:ident,
            $default_fn_str:literal,
            $null_deser_str:literal,
            $default_val:expr
        );* $(;)?
    ) => {
        // Generate default_keybind_*() functions
        $(
            fn $default_fn() -> String {
                $default_val.to_string()
            }
        )*

        // Generate deserialize_null_keybind_*() functions
        $(
            deserialize_null_with!($null_deser, String, $default_fn);
        )*

        /// Keybind settings structure.
        /// All fields use serde(default) + null deserializer for null handling.
        /// Generated by define_keybinds! macro.
        #[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
        pub struct KeybindSettings {
            $(
                #[serde(
                    default = $default_fn_str,
                    deserialize_with = $null_deser_str
                )]
                pub $field: String,
            )*
        }

        impl Default for KeybindSettings {
            fn default() -> Self {
                Self {
                    $( $field: $default_fn(), )*
                }
            }
        }
    };
}

define_keybinds! {
    copy,             default_keybind_copy,             deserialize_null_keybind_copy,
                      "default_keybind_copy",           "deserialize_null_keybind_copy",
                      "Ctrl+Shift+C";
    paste,            default_keybind_paste,            deserialize_null_keybind_paste,
                      "default_keybind_paste",          "deserialize_null_keybind_paste",
                      "Ctrl+Shift+V";
    select_all,       default_keybind_select_all,       deserialize_null_keybind_select_all,
                      "default_keybind_select_all",     "deserialize_null_keybind_select_all",
                      "Ctrl+Shift+A";
    search,           default_keybind_search,           deserialize_null_keybind_search,
                      "default_keybind_search",         "deserialize_null_keybind_search",
                      "Ctrl+Shift+F";
    new_tab,          default_keybind_new_tab,          deserialize_null_keybind_new_tab,
                      "default_keybind_new_tab",        "deserialize_null_keybind_new_tab",
                      "Ctrl+Shift+T";
    close_tab,        default_keybind_close_tab,        deserialize_null_keybind_close_tab,
                      "default_keybind_close_tab",      "deserialize_null_keybind_close_tab",
                      "Ctrl+Shift+W";
    next_tab,         default_keybind_next_tab,         deserialize_null_keybind_next_tab,
                      "default_keybind_next_tab",       "deserialize_null_keybind_next_tab",
                      "Ctrl+PageDown";
    prev_tab,         default_keybind_prev_tab,         deserialize_null_keybind_prev_tab,
                      "default_keybind_prev_tab",       "deserialize_null_keybind_prev_tab",
                      "Ctrl+PageUp";
    zoom_in,          default_keybind_zoom_in,          deserialize_null_keybind_zoom_in,
                      "default_keybind_zoom_in",        "deserialize_null_keybind_zoom_in",
                      "Ctrl+Plus";
    zoom_out,         default_keybind_zoom_out,         deserialize_null_keybind_zoom_out,
                      "default_keybind_zoom_out",       "deserialize_null_keybind_zoom_out",
                      "Ctrl+Minus";
    zoom_reset,       default_keybind_zoom_reset,       deserialize_null_keybind_zoom_reset,
                      "default_keybind_zoom_reset",     "deserialize_null_keybind_zoom_reset",
                      "Ctrl+0";
    toggle_fullscreen, default_keybind_toggle_fullscreen, deserialize_null_keybind_toggle_fullscreen,
                      "default_keybind_toggle_fullscreen", "deserialize_null_keybind_toggle_fullscreen",
                      "F11";
    open_settings,    default_keybind_open_settings,    deserialize_null_keybind_open_settings,
                      "default_keybind_open_settings",  "deserialize_null_keybind_open_settings",
                      "Ctrl+,";
    toggle_tab_bar,   default_keybind_toggle_tab_bar,   deserialize_null_keybind_toggle_tab_bar,
                      "default_keybind_toggle_tab_bar", "deserialize_null_keybind_toggle_tab_bar",
                      "Ctrl+Shift+B";
    jump_to_prev_prompt, default_keybind_jump_to_prev_prompt, deserialize_null_keybind_jump_to_prev_prompt,
                      "default_keybind_jump_to_prev_prompt", "deserialize_null_keybind_jump_to_prev_prompt",
                      "Ctrl+Shift+ArrowUp";
    jump_to_next_prompt, default_keybind_jump_to_next_prompt, deserialize_null_keybind_jump_to_next_prompt,
                      "default_keybind_jump_to_next_prompt", "deserialize_null_keybind_jump_to_next_prompt",
                      "Ctrl+Shift+ArrowDown";
    profile_selector, default_keybind_profile_selector, deserialize_null_keybind_profile_selector,
                      "default_keybind_profile_selector", "deserialize_null_keybind_profile_selector",
                      "Ctrl+Shift+P";
}

// ============================================================
// SSH Connection
// ============================================================

fn default_ssh_port() -> u16 {
    22
}

deserialize_null_with!(deserialize_null_ssh_port, u16, default_ssh_port);

/// Key-value pair for SSH -o options.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct SshOption {
    pub key: String,
    pub value: String,
}

/// SSH connection entry for remote host connections.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct SshConnection {
    pub name: String,
    pub hostname: String,
    #[serde(
        default = "default_ssh_port",
        deserialize_with = "deserialize_null_ssh_port"
    )]
    pub port: u16,
    #[serde(default, deserialize_with = "deserialize_null_default")]
    pub username: String,
    #[serde(default, deserialize_with = "deserialize_null_default")]
    pub identity_file: String,
    #[serde(default, deserialize_with = "deserialize_null_default")]
    pub ssh_options: Vec<SshOption>,
    /// Legacy field for backward compatibility. Read during deserialization but never serialized.
    #[serde(default, skip_serializing)]
    pub extra_options: String,
}

// ============================================================
// Profile
// ============================================================

/// Terminal profile for per-session shell configuration.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct Profile {
    pub name: String,
    #[serde(default, deserialize_with = "deserialize_null_default")]
    pub shell_path: String,
    #[serde(default, deserialize_with = "deserialize_null_default")]
    pub shell_args: Vec<String>,
    #[serde(default, deserialize_with = "deserialize_null_default")]
    pub env_vars: String,
    #[serde(default, deserialize_with = "deserialize_null_default")]
    pub working_directory: String,
    #[serde(default, deserialize_with = "deserialize_null_default")]
    pub is_default: bool,
    #[serde(default, deserialize_with = "deserialize_null_default")]
    pub ssh_connection_name: String,
    #[serde(default, deserialize_with = "deserialize_null_default")]
    pub wsl_distro_name: String,
}

// ============================================================
// Settings Structs
// ============================================================

/// Application settings structure for JSON serialization.
/// All fields use serde(default) + deserialize_null_default for backward compatibility.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AppSettings {
    // Font
    #[serde(
        default = "default_font_size",
        deserialize_with = "deserialize_null_font_size"
    )]
    pub font_size: u32,
    #[serde(default, deserialize_with = "deserialize_null_default")]
    pub font_family_primary: String,
    #[serde(default, deserialize_with = "deserialize_null_default")]
    pub font_family_secondary: String,
    #[serde(default, deserialize_with = "deserialize_null_default")]
    pub font_family_emoji: String,

    /// Legacy field for backward compatibility. Read during deserialization but never serialized.
    #[serde(default, skip_serializing)]
    pub(super) font_family: String,
    /// Deprecated: line_height is no longer configurable (always uses font metrics).
    /// Kept for backward compatibility with existing config files.
    #[serde(default, skip_serializing)]
    pub(super) _line_height: Option<f32>,

    // Theme / Color
    #[serde(default, deserialize_with = "deserialize_null_default")]
    pub ui_theme: UiTheme,
    #[serde(default, deserialize_with = "deserialize_null_default")]
    pub ui_theme_preset: UiThemePreset,
    #[serde(default, deserialize_with = "deserialize_null_default")]
    pub terminal_color_scheme: String,

    // Layout
    #[serde(
        default = "default_padding",
        deserialize_with = "deserialize_null_padding"
    )]
    pub padding: u32,
    #[serde(
        default = "default_scrollback_lines",
        deserialize_with = "deserialize_null_scrollback_lines"
    )]
    pub scrollback_lines: u32,
    #[serde(default, deserialize_with = "deserialize_null_default")]
    pub show_scrollbar: ScrollbarMode,
    #[serde(default = "default_true", deserialize_with = "deserialize_null_true")]
    pub show_tab_bar: bool,

    // Terminal
    #[serde(default, deserialize_with = "deserialize_null_default")]
    pub shell_path: String,
    #[serde(default, deserialize_with = "deserialize_null_default")]
    pub shell_args: Vec<String>,
    #[serde(default, deserialize_with = "deserialize_null_default")]
    pub cursor_style: CursorStyle,
    #[serde(default = "default_true", deserialize_with = "deserialize_null_true")]
    pub cursor_blink: bool,
    #[serde(
        default = "default_scroll_speed",
        deserialize_with = "deserialize_null_scroll_speed"
    )]
    pub scroll_speed: u32,
    #[serde(default, deserialize_with = "deserialize_null_default")]
    pub bell_action: BellAction,
    #[serde(default = "default_true", deserialize_with = "deserialize_null_true")]
    pub url_detection: bool,
    #[serde(default, deserialize_with = "deserialize_null_default")]
    pub copy_on_select: bool,
    #[serde(default = "default_true", deserialize_with = "deserialize_null_true")]
    pub fold_enabled: bool,
    #[serde(default = "default_true", deserialize_with = "deserialize_null_true")]
    pub file_path_detection: bool,
    #[serde(default = "default_true", deserialize_with = "deserialize_null_true")]
    pub bold_brightens_ansi_colors: bool,
    #[serde(default = "default_true", deserialize_with = "deserialize_null_true")]
    pub middle_click_paste: bool,
    #[serde(default = "default_true", deserialize_with = "deserialize_null_true")]
    pub shift_enter_as_alt_enter: bool,
    #[serde(skip)]
    pub ambiguous_width: bool,
    #[serde(
        default = "default_editor_command",
        deserialize_with = "deserialize_null_editor_command"
    )]
    pub editor_command: String,

    // IME
    #[serde(default = "default_true", deserialize_with = "deserialize_null_true")]
    pub skk_mode: bool,

    // Notification
    #[serde(default = "default_true", deserialize_with = "deserialize_null_true")]
    pub notification_enabled: bool,
    #[serde(default = "default_true", deserialize_with = "deserialize_null_true")]
    pub tab_activity_indicator: bool,
    #[serde(default = "default_true", deserialize_with = "deserialize_null_true")]
    pub notify_on_process_exit: bool,
    #[serde(default, deserialize_with = "deserialize_null_default")]
    pub notify_on_output: bool,
    #[serde(default = "default_true", deserialize_with = "deserialize_null_true")]
    pub notify_on_bell: bool,

    // Keybinds
    #[serde(default, deserialize_with = "deserialize_null_default")]
    pub keybinds: KeybindSettings,

    // Language
    #[serde(
        default = "default_language",
        deserialize_with = "deserialize_null_language"
    )]
    pub language: String,

    // UI Font
    #[serde(
        default = "default_ui_font_family",
        deserialize_with = "deserialize_null_ui_font_family"
    )]
    pub ui_font_family: String,

    // Custom Color Schemes
    #[serde(default, deserialize_with = "deserialize_null_default")]
    pub custom_color_schemes: Vec<UserColorScheme>,

    // Profiles
    #[serde(default, deserialize_with = "deserialize_null_default")]
    pub profiles: Vec<Profile>,

    // SSH
    #[serde(default, deserialize_with = "deserialize_null_default")]
    pub ssh_command_path: String,
    #[serde(default, deserialize_with = "deserialize_null_default")]
    pub ssh_connections: Vec<SshConnection>,

    // SFTP
    #[serde(
        default = "default_sftp_max_concurrent_uploads",
        deserialize_with = "deserialize_null_sftp_max_concurrent_uploads"
    )]
    pub sftp_max_concurrent_uploads: u16,

    // OSC 52 Clipboard
    #[serde(default = "default_true", deserialize_with = "deserialize_null_true")]
    pub clipboard_read_osc52: bool,
    #[serde(
        default = "default_clipboard_max_size_osc52",
        deserialize_with = "deserialize_null_clipboard_max_size_osc52"
    )]
    pub clipboard_max_size_osc52: u32,

    // Log Recording
    #[serde(default, deserialize_with = "deserialize_null_default")]
    pub log_recording_enabled: bool,

    // Markdown Viewer
    #[serde(default = "default_true", deserialize_with = "deserialize_null_true")]
    pub markdown_theme_follow_ui: bool,
    #[serde(default, deserialize_with = "deserialize_null_default")]
    pub markdown_theme: UiTheme,
    #[serde(default, deserialize_with = "deserialize_null_default")]
    pub markdown_theme_preset: UiThemePreset,
    #[serde(
        default = "default_markdown_body_font_family",
        deserialize_with = "deserialize_null_markdown_body_font_family"
    )]
    pub markdown_body_font_family: String,
    #[serde(
        default = "default_markdown_code_font_family",
        deserialize_with = "deserialize_null_markdown_code_font_family"
    )]
    pub markdown_code_font_family: String,
    #[serde(
        default = "default_markdown_emoji_font_family",
        deserialize_with = "deserialize_null_markdown_emoji_font_family"
    )]
    pub markdown_emoji_font_family: String,
    #[serde(
        default = "default_markdown_font_size",
        deserialize_with = "deserialize_null_markdown_font_size"
    )]
    pub markdown_font_size: u32,

    // Mux (multiplexer) settings
    #[serde(default, deserialize_with = "deserialize_null_default")]
    pub mux: MuxSettings,
}

/// Multiplexer settings.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MuxSettings {
    #[serde(default = "default_mux_prefix")]
    pub prefix: String,
    #[serde(default)]
    pub base_index: u32,
    #[serde(default = "default_true")]
    pub mouse: bool,
    #[serde(default = "default_mux_status_position")]
    pub status_position: String,
    #[serde(default)]
    pub tab_always_expand: bool,
}

fn default_mux_prefix() -> String {
    "ctrl+b".to_string()
}

fn default_mux_status_position() -> String {
    "bottom".to_string()
}

impl Default for MuxSettings {
    fn default() -> Self {
        Self {
            prefix: default_mux_prefix(),
            base_index: 0,
            mouse: true,
            status_position: default_mux_status_position(),
            tab_always_expand: false,
        }
    }
}

impl Default for AppSettings {
    fn default() -> Self {
        Self {
            font_size: default_font_size(),
            font_family_primary: String::new(),
            font_family_secondary: String::new(),
            font_family_emoji: String::new(),
            font_family: String::new(),
            _line_height: None,
            ui_theme: UiTheme::default(),
            ui_theme_preset: UiThemePreset::default(),
            terminal_color_scheme: String::new(),
            padding: default_padding(),
            scrollback_lines: default_scrollback_lines(),
            show_scrollbar: ScrollbarMode::default(),
            show_tab_bar: default_true(),
            shell_path: String::new(),
            shell_args: Vec::new(),
            cursor_style: CursorStyle::default(),
            cursor_blink: default_true(),
            scroll_speed: default_scroll_speed(),
            bell_action: BellAction::default(),
            url_detection: default_true(),
            copy_on_select: false,
            keybinds: KeybindSettings::default(),
            language: default_language(),
            ui_font_family: default_ui_font_family(),
            custom_color_schemes: Vec::new(),
            profiles: Vec::new(),
            ssh_command_path: String::new(),
            ssh_connections: Vec::new(),
            sftp_max_concurrent_uploads: default_sftp_max_concurrent_uploads(),
            markdown_theme_follow_ui: default_true(),
            markdown_theme: UiTheme::default(),
            markdown_theme_preset: UiThemePreset::default(),
            markdown_body_font_family: default_markdown_body_font_family(),
            markdown_code_font_family: default_markdown_code_font_family(),
            markdown_emoji_font_family: default_markdown_emoji_font_family(),
            markdown_font_size: default_markdown_font_size(),
            fold_enabled: default_true(),
            file_path_detection: default_true(),
            bold_brightens_ansi_colors: default_true(),
            middle_click_paste: default_true(),
            shift_enter_as_alt_enter: default_true(),
            ambiguous_width: default_true(),
            editor_command: default_editor_command(),
            skk_mode: default_true(),
            notification_enabled: default_true(),
            tab_activity_indicator: default_true(),
            notify_on_process_exit: default_true(),
            notify_on_output: false,
            notify_on_bell: default_true(),
            clipboard_read_osc52: default_true(),
            clipboard_max_size_osc52: default_clipboard_max_size_osc52(),
            log_recording_enabled: false,
            mux: MuxSettings::default(),
        }
    }
}
