//! Build script for native-poc.
//!
//! Generates a compile-time manifest of the embedded Markdown viewer
//! bundle (`viewer/dist/`, produced by `bun run build:viewer`). The
//! bundler emits content-hashed filenames, so we cannot `include_bytes!`
//! fixed paths; instead we walk the directory at build time and emit a
//! `&[ViewerAsset]` slice that `src/viewer/assets.rs` re-exports.
//!
//! If `viewer/dist/` is absent (e.g. a Rust-only `cargo check` before the
//! bundle is built), the manifest is empty and the viewer serves a clear
//! fallback. This keeps `cargo check`/`cargo test` working without Bun.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let dist = manifest_dir.join("viewer").join("dist");
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let dest = out_dir.join("viewer_assets.rs");

    // Re-run if the bundle changes.
    println!("cargo:rerun-if-changed=viewer/dist");

    let mut entries: Vec<(String, PathBuf)> = Vec::new();
    if dist.is_dir() {
        collect(&dist, &dist, &mut entries);
    } else {
        let profile = env::var("PROFILE").unwrap_or_default();
        let msg = "viewer/dist is missing — run `bun run build:viewer` first to embed the \
                   Markdown viewer assets. Without this the viewer will always fail at runtime.";
        if profile == "release" {
            panic!("{}", msg);
        } else {
            println!("cargo:warning={}", msg);
        }
    }
    entries.sort_by(|a, b| a.0.cmp(&b.0));

    let mut code = String::new();
    code.push_str(
        "// @generated by build.rs — embedded Markdown viewer bundle manifest.\n\
         /// One embedded viewer-bundle file: (relative path, bytes, content type).\n\
         pub struct ViewerAsset {\n\
         \x20   pub path: &'static str,\n\
         \x20   pub bytes: &'static [u8],\n\
         \x20   pub content_type: &'static str,\n\
         }\n\n\
         /// All embedded viewer-bundle files. Empty when `viewer/dist` was\n\
         /// absent at build time (Rust-only build without `bun run build:viewer`).\n\
         pub static VIEWER_ASSETS: &[ViewerAsset] = &[\n",
    );
    for (rel, abs) in &entries {
        let abs_str = abs.to_string_lossy().replace('\\', "/");
        let ct = content_type(rel);
        code.push_str(&format!(
            "    ViewerAsset {{ path: {rel:?}, bytes: include_bytes!({abs_str:?}), content_type: {ct:?} }},\n"
        ));
        println!("cargo:rerun-if-changed=viewer/dist/{rel}");
    }
    code.push_str("];\n");

    fs::write(&dest, code).expect("write viewer_assets.rs");
}

fn collect(root: &Path, dir: &Path, out: &mut Vec<(String, PathBuf)>) {
    let Ok(read) = fs::read_dir(dir) else {
        return;
    };
    for entry in read.flatten() {
        let path = entry.path();
        if path.is_dir() {
            collect(root, &path, out);
        } else if path.is_file() {
            if let Ok(rel) = path.strip_prefix(root) {
                let rel = rel.to_string_lossy().replace('\\', "/");
                out.push((rel, path));
            }
        }
    }
}

fn content_type(path: &str) -> &'static str {
    match path.rsplit('.').next().unwrap_or("") {
        "html" => "text/html; charset=utf-8",
        "js" | "mjs" => "text/javascript; charset=utf-8",
        "css" => "text/css; charset=utf-8",
        "json" | "map" => "application/json; charset=utf-8",
        "wasm" => "application/wasm",
        "svg" => "image/svg+xml",
        "png" => "image/png",
        "jpg" | "jpeg" => "image/jpeg",
        "gif" => "image/gif",
        "webp" => "image/webp",
        "woff" => "font/woff",
        "woff2" => "font/woff2",
        "ttf" => "font/ttf",
        "otf" => "font/otf",
        _ => "application/octet-stream",
    }
}
