//! Embedded Markdown viewer bundle accessor.
//!
//! The bundle (`viewer/dist/`, produced by `bun run build:viewer`) is
//! walked at build time by `build.rs`, which emits a `VIEWER_ASSETS`
//! manifest of (path, bytes, content-type). The child viewer's custom URI
//! scheme (Phase 4) resolves in-bundle paths through [`asset`].

// `VIEWER_ASSETS` / `ViewerAsset` are generated by build.rs into OUT_DIR.
include!(concat!(env!("OUT_DIR"), "/viewer_assets.rs"));

/// The bundle's HTML entry path.
pub const INDEX_PATH: &str = "index.html";

/// Look up an embedded bundle file by its in-bundle relative path
/// (e.g. `index.html`, `index-<hash>.js`). Returns the bytes and the
/// content type, or `None` if no such asset is embedded.
///
/// A leading `/` and a `./` prefix are tolerated so the accessor matches
/// both `emterm-viewer:///index.html` and `./index-<hash>.js` request
/// shapes produced by the bundler-generated HTML.
pub fn asset(path: &str) -> Option<(&'static [u8], &'static str)> {
    let normalized = normalize(path);
    VIEWER_ASSETS
        .iter()
        .find(|a| a.path == normalized)
        .map(|a| (a.bytes, a.content_type))
}

/// Strip a leading `/` or `./` and collapse an empty path to the index.
fn normalize(path: &str) -> &str {
    let p = path.strip_prefix("./").unwrap_or(path);
    let p = p.strip_prefix('/').unwrap_or(p);
    if p.is_empty() { INDEX_PATH } else { p }
}

/// Whether the viewer bundle was embedded at build time. `false` means
/// `viewer/dist` was missing during the Rust build (no `bun run
/// build:viewer`); the child viewer must surface a clear error instead of
/// a blank window.
pub fn is_embedded() -> bool {
    !VIEWER_ASSETS.is_empty()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn normalize_strips_prefixes_and_defaults_to_index() {
        assert_eq!(normalize("index.html"), "index.html");
        assert_eq!(normalize("/index.html"), "index.html");
        assert_eq!(normalize("./index.html"), "index.html");
        assert_eq!(normalize("/"), INDEX_PATH);
        assert_eq!(normalize(""), INDEX_PATH);
        assert_eq!(normalize("./index-abc.js"), "index-abc.js");
    }

    #[test]
    fn unknown_asset_returns_none() {
        assert!(asset("does-not-exist.bin").is_none());
    }

    // When the bundle is embedded (CI / release build with the bundle
    // present), the index must resolve. We only assert this conditionally
    // so a Rust-only `cargo test` without `bun run build:viewer` still
    // passes (is_embedded() == false).
    #[test]
    fn index_resolves_when_bundle_embedded() {
        if is_embedded() {
            let (bytes, ct) = asset(INDEX_PATH).expect("index.html embedded");
            assert!(!bytes.is_empty());
            assert!(ct.starts_with("text/html"));
            // The "/" and "" forms resolve to the same index bytes.
            assert_eq!(asset("/").map(|(b, _)| b), Some(bytes));
        }
    }
}
