//! Embedded settings-window bundle accessor.
//!
//! The bundle (`settings/dist/`, produced by `bun run build:settings`) is
//! walked at build time by `build.rs`, which emits a `SETTINGS_ASSETS`
//! manifest of (path, bytes, content-type). The child settings window's
//! custom URI scheme resolves in-bundle paths through [`asset`].

// `SETTINGS_ASSETS` / `ViewerAsset` are generated by build.rs into OUT_DIR.
include!(concat!(env!("OUT_DIR"), "/settings_assets.rs"));

/// The bundle's HTML entry path.
pub const INDEX_PATH: &str = "index.html";

/// True when the settings bundle was embedded at build time.
pub fn is_embedded() -> bool {
    !SETTINGS_ASSETS.is_empty()
}

/// Look up an embedded bundle file by its in-bundle relative path
/// (e.g. `index.html`, `index-<hash>.js`). Returns the bytes and the
/// content type, or `None` if no such asset is embedded.
///
/// A leading `/` and a `./` prefix are tolerated so the accessor matches
/// both `emterm-settings:///index.html` and `./index-<hash>.js` request
/// shapes produced by the bundler-generated HTML.
pub fn asset(path: &str) -> Option<(&'static [u8], &'static str)> {
    let normalized = normalize(path);
    SETTINGS_ASSETS
        .iter()
        .find(|a| a.path == normalized)
        .map(|a| (a.bytes, a.content_type))
}

/// Strip a leading `/` or `./` and collapse an empty path to the index.
fn normalize(path: &str) -> &str {
    let p = path.strip_prefix('/').unwrap_or(path);
    let p = p.strip_prefix("./").unwrap_or(p);
    if p.is_empty() {
        INDEX_PATH
    } else {
        p
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn normalize_strips_prefixes_and_defaults_to_index() {
        assert_eq!(normalize("/index.html"), "index.html");
        assert_eq!(normalize("./chunk.js"), "chunk.js");
        assert_eq!(normalize(""), INDEX_PATH);
        assert_eq!(normalize("/"), INDEX_PATH);
    }
}
